pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/.m2
    volumes:
      - /tmp/cache:/cache

  build:
    image: maven:3-jdk-8-alpine
    environment:
      - MAVEN_CONFIG=/drone/.m2
    commands:
      - pwd
      - mvn -B install -Dmaven.repo.local=/drone/.m2

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/.m2
    volumes:
      - /tmp/cache:/cache