version: 2
jobs:
  build:
    working_directory: ~/log-parser
    docker:
      - image: openjdk:8-jdk-alpine
    steps:
      - checkout
      - restore_cache:
          key: log-parser-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: log-parser-{{ checksum "pom.xml" }}
      - run: mvn verify
      - save_cache:
          paths:
            - ~/.m2
          key: log-parser-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
      - store_test_results:
          path: target/failsafe-reports
